name: salesforce portfolio
favicon: null
layout_spectrum: 0.7657897260505706
typography_spectrum: 0.21218208316713572
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6981967771425843
  lightness: 0.5396589254960418
  saturation: 0.21848959918133914
  rhythmicContrast: 0.2588935212697834
purpose: []
